import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import NextAuthProvider from "@/providers/NextAuthProvider";
import TopMenu  from "@/components/TopMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UFA888's Hotel Booking System",
  description: "Generated by create next app",
};

export default async function LayoutWithNavbar({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <NextAuthProvider session={session}>
      <TopMenu />
      <div className="mt-[100px]">{children}</div>
    </NextAuthProvider>
    
  );
}
